apiVersion: v1
kind: ConfigMap
metadata:
  name: booking-orchestrator-env
data:
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: in_memory
  services__minio__http__0: "minio-mmr-0.minio-mmr:9000"
  OTEL_EXPORTER_OTLP_ENDPOINT: http://aspire-dashboard:18889
  OTEL_SERVICE_NAME: bookingOrchestrator
  ASPNETCORE_URLS: http://+:8080;
  SCHEDULE_API_URL: "http://sked-tst.dit.urfu.ru:8100"
