apiVersion: v1
kind: ConfigMap
metadata:
  name: booking-orchestrator-env
data:
  # kv format
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: true
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: true
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: in_memory
  SCHEDULE_API_USERNAME: mediaroom
  SCHEDULE_API_PASSWORD: r3cife0a9h
  MINIO_ACCESS_KEY: root
  MINIO_SECRET_KEY: root1234
  services__minio__http__0: http://minio:9000s
  services__minio__admin__0: minio:9001
  OTEL_EXPORTER_OTLP_ENDPOINT: http://aspire-dashboard:18889
  OTEL_SERVICE_NAME: bookingOrchestrator
  ASPNETCORE_URLS: http://+:8080;
