---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-orchestrator
  labels:
    app: booking-orchestrator
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: booking-orchestrator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: booking-orchestrator
    spec:
      containers:
      - name: booking-orchestrator
        image: cr.yandex/crppvgkl2ft86f0jdvnc/bookingorchestrator:1.0.0
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: booking-orchestrator-env
        - secretRef:
            name: minio-access-keys-secrets
        - secretRef:
            name: postgres-mmr-connection-string
        - secretRef:
            name: schedule-api-secrets
      terminationGracePeriodSeconds: 180