apiVersion: v1
kind: ConfigMap
metadata:
  name: webapi-env
data:
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"

  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
  ASPNETCORE_ENVIRONMENT: "Development"
  services__minio__http__0: "minio-mmr-0.minio-mmr:9000"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://env-dashboard:18889"
  OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
  OTEL_SERVICE_NAME: "webapi"