apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-mmr-env
data:
  POSTGRES_HOST_AUTH_METHOD: scram-sha-256
#  POSTGRES_INITDB_ARGS: "--auth-host: scram-sha-256 --auth-local: scram-sha-256"
  OTEL_EXPORTER_OTLP_ENDPOINT: http://aspire-dashboard:18889
  OTEL_SERVICE_NAME: postgres-mmr
  POSTGRES_DB: mmr
  PGDATA: /var/lib/postgresql/data/pgdata
  
